import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import NavBar from "./components/navbar";
import Footer from "./components/footer";
import "./globals.css";

const nunito = Nunito({
    subsets: ["latin"],
    weight: ["400", "600", "700", "800", "900"],
    variable: "--font-nunito",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body className={`${nunito.variable} antialiased`}>
                <NavBar /> {}
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
